name: Create all Releases

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: "App Semantic Version."
        required: true
        type: string
      tag:
        description: "Tag of the release"
        required: true
        type: string

jobs:
  build_some_linux:
    uses: ./.github/workflows/workflow_build_manual.yml
    with:
      operating_system: "debian-11"
      app_version: ${{ inputs.app_version }}
      tag: ${{ inputs.tag }}
